- name: check if go ipfs installed extraction
  stat: path=/usr/local/bin/ipfs
  register: go_ipfs_installed

- name: download go-ipfs {{  go_ipfs_version  }}
  get_url: url=https://dist.ipfs.io/go-ipfs/{{  go_ipfs_version  }}/go-ipfs_{{  go_ipfs_version  }}_linux-amd64.tar.gz dest=/tmp/go_ipfs{{ go_ipfs_version }}.tar.gz validate_certs=no
  when: not go_ipfs_installed.stat.exists

- name: unarchive go-ipfs {{  go_ipfs_version  }}
  unarchive: src=/tmp/go_ipfs{{ go_ipfs_version }}.tar.gz dest=/tmp copy=no
  when: not go_ipfs_installed.stat.exists

- name: install go-ipfs {{  go_ipfs_version  }}
  command: chdir=/tmp/go-ipfs  mv ipfs /usr/local/bin/ipfs
  when: not go_ipfs_installed.stat.exists